-- INSERT INTO avatar_image (file_path, file_name, file_size) VALUES
--                                                                ('/uploads/avatars/', 'avatar_1.jpg', 102400),
--                                                                ('/uploads/avatars/', 'avatar_2.png', 256000),
--                                                                ('/uploads/avatars/', 'avatar_3.jpg', 180000);
--
-- INSERT INTO city (name) VALUES
--                             ('Москва'),
--                             ('Санкт-Петербург'),
--                             ('Казань');
--
-- INSERT INTO role (name) VALUES
--                             ('BUYER'),
--                             ('SELLER'),
--                             ('ADMIN');