create table if not exists role
(
    id      bigint          primary key generated by default as identity,
    name    varchar(255)    not null
);

comment on table role is 'Таблица ролей пользователей';

comment on column role.id is 'Уникальный идентификатор роли';
comment on column role.name is 'Название роли';