create table if not exists avatar_image
(
    id          bigint          primary key generated by default as identity,
    file_path   varchar(511)    not null,
    file_name   varchar(255)    not null,
    file_size   bigint          not null
);

comment on table avatar_image is 'Таблица, содержащая информацию об аватарах пользователей';

comment on column avatar_image.id is 'Уникальный идентификатор аватара';
comment on column avatar_image.file_path is 'Путь к файлу аватара';
comment on column avatar_image.file_name is 'Имя файла аватара';
comment on column avatar_image.file_size is 'Размер файла в байтах';