create table if not exists "user"
(
	id					bigint			primary key generated by default as identity,
	avatar_id			bigint			references avatar_image(id),
	created_at			timestamptz		not null,
	email 				varchar(255)	not null,
	password			varchar(255)	not null,
	display_name		varchar(255)	not null,
	phone_number		varchar(255)
);

comment on table "user" is 'Таблица, содержащая информацию о пользователях';

comment on column "user".id is 'Уникальный идентификатор пользователя';
comment on column "user".avatar_id is 'Внешний ключ на аватар';
comment on column "user".created_at is 'Дата регистрации пользователя';
comment on column "user".email is 'Почта пользователя';
comment on column "user".password is 'Хэш пароля пользователя';
comment on column "user".display_name is 'Имя, отображаемое другим пользователям';
comment on column "user".phone_number is 'Телефонный номер пользователя';

