create table if not exists city
(
    id      bigint          primary key generated by default as identity,
    name    varchar(255)    not null
);

comment on table city is 'Таблица, содержащая информацию о городах';

comment on column city.id is 'Уникальный идентификатор города';
comment on column city.name is 'Название города';